<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('countries')->delete();

		$countries = array(
            array("ID" => "1","iso" => "AF","name" => "Afghanistan","iso3" => "AFG"),
            array("ID" => "2","iso" => "AL","name" => "Albania","iso3" => "ALB"),
            array("ID" => "3","iso" => "DZ","name" => "Algeria","iso3" => "DZA"),
            array("ID" => "4","iso" => "AS","name" => "American Samoa","iso3" => "ASM"),
            array("ID" => "5","iso" => "AD","name" => "Andorra","iso3" => "AND"),
            array("ID" => "6","iso" => "AO","name" => "Angola","iso3" => "AGO"),
            array("ID" => "7","iso" => "AI","name" => "Anguilla","iso3" => "AIA"),
            array("ID" => "8","iso" => "AQ","name" => "Antarctica","iso3" => ""),
            array("ID" => "9","iso" => "AG","name" => "Antigua and Barbuda","iso3" => "ATG"),
            array("ID" => "10","iso" => "AR","name" => "Argentina","iso3" => "ARG"),
            array("ID" => "11","iso" => "AM","name" => "Armenia","iso3" => "ARM"),
            array("ID" => "12","iso" => "AW","name" => "Aruba","iso3" => "ABW"),
            array("ID" => "13","iso" => "AU","name" => "Australia","iso3" => "AUS"),
            array("ID" => "14","iso" => "AT","name" => "Austria","iso3" => "AUT"),
            array("ID" => "15","iso" => "AZ","name" => "Azerbaijan","iso3" => "AZE"),
            array("ID" => "16","iso" => "BS","name" => "Bahamas","iso3" => "BHS"),
            array("ID" => "17","iso" => "BH","name" => "Bahrain","iso3" => "BHR"),
            array("ID" => "18","iso" => "BD","name" => "Bangladesh","iso3" => "BGD"),
            array("ID" => "19","iso" => "BB","name" => "Barbados","iso3" => "BRB"),
            array("ID" => "20","iso" => "BY","name" => "Belarus","iso3" => "BLR"),
            array("ID" => "21","iso" => "BE","name" => "Belgium","iso3" => "BEL"),
            array("ID" => "22","iso" => "BZ","name" => "Belize","iso3" => "BLZ"),
            array("ID" => "23","iso" => "BJ","name" => "Benin","iso3" => "BEN"),
            array("ID" => "24","iso" => "BM","name" => "Bermuda","iso3" => "BMU"),
            array("ID" => "25","iso" => "BT","name" => "Bhutan","iso3" => "BTN"),
            array("ID" => "26","iso" => "BO","name" => "Bolivia","iso3" => "BOL"),
            array("ID" => "27","iso" => "BA","name" => "Bosnia and Herzegovina","iso3" => "BIH"),
            array("ID" => "28","iso" => "BW","name" => "Botswana","iso3" => "BWA"),
            array("ID" => "29","iso" => "BV","name" => "Bouvet Island","iso3" => ""),
            array("ID" => "30","iso" => "BR","name" => "Brazil","iso3" => "BRA"),
            array("ID" => "31","iso" => "IO","name" => "British Indian Ocean Territory","iso3" => ""),
            array("ID" => "32","iso" => "BN","name" => "Brunei Darussalam","iso3" => "BRN"),
            array("ID" => "33","iso" => "BG","name" => "Bulgaria","iso3" => "BGR"),
            array("ID" => "34","iso" => "BF","name" => "Burkina Faso","iso3" => "BFA"),
            array("ID" => "35","iso" => "BI","name" => "Burundi","iso3" => "BDI"),
            array("ID" => "36","iso" => "KH","name" => "Cambodia","iso3" => "KHM"),
            array("ID" => "37","iso" => "CM","name" => "Cameroon","iso3" => "CMR"),
            array("ID" => "38","iso" => "CA","name" => "Canada","iso3" => "CAN"),
            array("ID" => "39","iso" => "CV","name" => "Cape Verde","iso3" => "CPV"),
            array("ID" => "40","iso" => "KY","name" => "Cayman Islands","iso3" => "CYM"),
            array("ID" => "41","iso" => "CF","name" => "Central African Republic","iso3" => "CAF"),
            array("ID" => "42","iso" => "TD","name" => "Chad","iso3" => "TCD"),
            array("ID" => "43","iso" => "CL","name" => "Chile","iso3" => "CHL"),
            array("ID" => "44","iso" => "CN","name" => "China","iso3" => "CHN"),
            array("ID" => "45","iso" => "CX","name" => "Christmas Island","iso3" => ""),
            array("ID" => "46","iso" => "CC","name" => "Cocos (Keeling) Islands","iso3" => ""),
            array("ID" => "47","iso" => "CO","name" => "Colombia","iso3" => "COL"),
            array("ID" => "48","iso" => "KM","name" => "Comoros","iso3" => "COM"),
            array("ID" => "49","iso" => "CG","name" => "Congo","iso3" => "COG"),
            array("ID" => "50","iso" => "CD","name" => "Congo, the Democratic Republic of the","iso3" => "COD"),
            array("ID" => "51","iso" => "CK","name" => "Cook Islands","iso3" => "COK"),
            array("ID" => "52","iso" => "CR","name" => "Costa Rica","iso3" => "CRI"),
            array("ID" => "53","iso" => "CI","name" => "Cote D'Ivoire","iso3" => "CIV"),
            array("ID" => "54","iso" => "HR","name" => "Croatia","iso3" => "HRV"),
            array("ID" => "55","iso" => "CU","name" => "Cuba","iso3" => "CUB"),
            array("ID" => "56","iso" => "CY","name" => "Cyprus","iso3" => "CYP"),
            array("ID" => "57","iso" => "CZ","name" => "Czech Republic","iso3" => "CZE"),
            array("ID" => "58","iso" => "DK","name" => "Denmark","iso3" => "DNK"),
            array("ID" => "59","iso" => "DJ","name" => "Djibouti","iso3" => "DJI"),
            array("ID" => "60","iso" => "DM","name" => "Dominica","iso3" => "DMA"),
            array("ID" => "61","iso" => "DO","name" => "Dominican Republic","iso3" => "DOM"),
            array("ID" => "62","iso" => "EC","name" => "Ecuador","iso3" => "ECU"),
            array("ID" => "63","iso" => "EG","name" => "Egypt","iso3" => "EGY"),
            array("ID" => "64","iso" => "SV","name" => "El Salvador","iso3" => "SLV"),
            array("ID" => "65","iso" => "GQ","name" => "Equatorial Guinea","iso3" => "GNQ"),
            array("ID" => "66","iso" => "ER","name" => "Eritrea","iso3" => "ERI"),
            array("ID" => "67","iso" => "EE","name" => "Estonia","iso3" => "EST"),
            array("ID" => "68","iso" => "ET","name" => "Ethiopia","iso3" => "ETH"),
            array("ID" => "69","iso" => "FK","name" => "Falkland Islands (Malvinas)","iso3" => "FLK"),
            array("ID" => "70","iso" => "FO","name" => "Faroe Islands","iso3" => "FRO"),
            array("ID" => "71","iso" => "FJ","name" => "Fiji","iso3" => "FJI"),
            array("ID" => "72","iso" => "FI","name" => "Finland","iso3" => "FIN"),
            array("ID" => "73","iso" => "FR","name" => "France","iso3" => "FRA"),
            array("ID" => "74","iso" => "GF","name" => "French Guiana","iso3" => "GUF"),
            array("ID" => "75","iso" => "PF","name" => "French Polynesia","iso3" => "PYF"),
            array("ID" => "76","iso" => "TF","name" => "French Southern Territories","iso3" => ""),
            array("ID" => "77","iso" => "GA","name" => "Gabon","iso3" => "GAB"),
            array("ID" => "78","iso" => "GM","name" => "Gambia","iso3" => "GMB"),
            array("ID" => "79","iso" => "GE","name" => "Georgia","iso3" => "GEO"),
            array("ID" => "80","iso" => "DE","name" => "Germany","iso3" => "DEU"),
            array("ID" => "81","iso" => "GH","name" => "Ghana","iso3" => "GHA"),
            array("ID" => "82","iso" => "GI","name" => "Gibraltar","iso3" => "GIB"),
            array("ID" => "83","iso" => "GR","name" => "Greece","iso3" => "GRC"),
            array("ID" => "84","iso" => "GL","name" => "Greenland","iso3" => "GRL"),
            array("ID" => "85","iso" => "GD","name" => "Grenada","iso3" => "GRD"),
            array("ID" => "86","iso" => "GP","name" => "Guadeloupe","iso3" => "GLP"),
            array("ID" => "87","iso" => "GU","name" => "Guam","iso3" => "GUM"),
            array("ID" => "88","iso" => "GT","name" => "Guatemala","iso3" => "GTM"),
            array("ID" => "89","iso" => "GN","name" => "Guinea","iso3" => "GIN"),
            array("ID" => "90","iso" => "GW","name" => "Guinea-Bissau","iso3" => "GNB"),
            array("ID" => "91","iso" => "GY","name" => "Guyana","iso3" => "GUY"),
            array("ID" => "92","iso" => "HT","name" => "Haiti","iso3" => "HTI"),
            array("ID" => "93","iso" => "HM","name" => "Heard Island and Mcdonald Islands","iso3" => ""),
            array("ID" => "94","iso" => "VA","name" => "Holy See (Vatican City State)","iso3" => "VAT"),
            array("ID" => "95","iso" => "HN","name" => "Honduras","iso3" => "HND"),
            array("ID" => "96","iso" => "HK","name" => "Hong Kong","iso3" => "HKG"),
            array("ID" => "97","iso" => "HU","name" => "Hungary","iso3" => "HUN"),
            array("ID" => "98","iso" => "IS","name" => "Iceland","iso3" => "ISL"),
            array("ID" => "99","iso" => "IN","name" => "India","iso3" => "IND"),
            array("ID" => "100","iso" => "ID","name" => "Indonesia","iso3" => "IDN"),
            array("ID" => "101","iso" => "IR","name" => "Iran, Islamic Republic of","iso3" => "IRN"),
            array("ID" => "102","iso" => "IQ","name" => "Iraq","iso3" => "IRQ"),
            array("ID" => "103","iso" => "IE","name" => "Ireland","iso3" => "IRL"),
            array("ID" => "104","iso" => "IL","name" => "Israel","iso3" => "ISR"),
            array("ID" => "105","iso" => "IT","name" => "Italy","iso3" => "ITA"),
            array("ID" => "106","iso" => "JM","name" => "Jamaica","iso3" => "JAM"),
            array("ID" => "107","iso" => "JP","name" => "Japan","iso3" => "JPN"),
            array("ID" => "108","iso" => "JO","name" => "Jordan","iso3" => "JOR"),
            array("ID" => "109","iso" => "KZ","name" => "Kazakhstan","iso3" => "KAZ"),
            array("ID" => "110","iso" => "KE","name" => "Kenya","iso3" => "KEN"),
            array("ID" => "111","iso" => "KI","name" => "Kiribati","iso3" => "KIR"),
            array("ID" => "112","iso" => "KP","name" => "Korea, Democratic People's Republic of","iso3" => "PRK"),
            array("ID" => "113","iso" => "KR","name" => "Korea, Republic of","iso3" => "KOR"),
            array("ID" => "114","iso" => "KW","name" => "Kuwait","iso3" => "KWT"),
            array("ID" => "115","iso" => "KG","name" => "Kyrgyzstan","iso3" => "KGZ"),
            array("ID" => "116","iso" => "LA","name" => "Lao People's Democratic Republic","iso3" => "LAO"),
            array("ID" => "117","iso" => "LV","name" => "Latvia","iso3" => "LVA"),
            array("ID" => "118","iso" => "LB","name" => "Lebanon","iso3" => "LBN"),
            array("ID" => "119","iso" => "LS","name" => "Lesotho","iso3" => "LSO"),
            array("ID" => "120","iso" => "LR","name" => "Liberia","iso3" => "LBR"),
            array("ID" => "121","iso" => "LY","name" => "Libyan Arab Jamahiriya","iso3" => "LBY"),
            array("ID" => "122","iso" => "LI","name" => "Liechtenstein","iso3" => "LIE"),
            array("ID" => "123","iso" => "LT","name" => "Lithuania","iso3" => "LTU"),
            array("ID" => "124","iso" => "LU","name" => "Luxembourg","iso3" => "LUX"),
            array("ID" => "125","iso" => "MO","name" => "Macao","iso3" => "MAC"),
            array("ID" => "126","iso" => "MK","name" => "Macedonia, the Former Yugoslav Republic of","iso3" => "MKD"),
            array("ID" => "127","iso" => "MG","name" => "Madagascar","iso3" => "MDG"),
            array("ID" => "128","iso" => "MW","name" => "Malawi","iso3" => "MWI"),
            array("ID" => "129","iso" => "MY","name" => "Malaysia","iso3" => "MYS"),
            array("ID" => "130","iso" => "MV","name" => "Maldives","iso3" => "MDV"),
            array("ID" => "131","iso" => "ML","name" => "Mali","iso3" => "MLI"),
            array("ID" => "132","iso" => "MT","name" => "Malta","iso3" => "MLT"),
            array("ID" => "133","iso" => "MH","name" => "Marshall Islands","iso3" => "MHL"),
            array("ID" => "134","iso" => "MQ","name" => "Martinique","iso3" => "MTQ"),
            array("ID" => "135","iso" => "MR","name" => "Mauritania","iso3" => "MRT"),
            array("ID" => "136","iso" => "MU","name" => "Mauritius","iso3" => "MUS"),
            array("ID" => "137","iso" => "YT","name" => "Mayotte","iso3" => ""),
            array("ID" => "138","iso" => "MX","name" => "Mexico","iso3" => "MEX"),
            array("ID" => "139","iso" => "FM","name" => "Micronesia, Federated States of","iso3" => "FSM"),
            array("ID" => "140","iso" => "MD","name" => "Moldova, Republic of","iso3" => "MDA"),
            array("ID" => "141","iso" => "MC","name" => "Monaco","iso3" => "MCO"),
            array("ID" => "142","iso" => "MN","name" => "Mongolia","iso3" => "MNG"),
            array("ID" => "143","iso" => "MS","name" => "Montserrat","iso3" => "MSR"),
            array("ID" => "144","iso" => "MA","name" => "Morocco","iso3" => "MAR"),
            array("ID" => "145","iso" => "MZ","name" => "Mozambique","iso3" => "MOZ"),
            array("ID" => "146","iso" => "MM","name" => "Myanmar","iso3" => "MMR"),
            array("ID" => "147","iso" => "NA","name" => "Namibia","iso3" => "NAM"),
            array("ID" => "148","iso" => "NR","name" => "Nauru","iso3" => "NRU"),
            array("ID" => "149","iso" => "NP","name" => "Nepal","iso3" => "NPL"),
            array("ID" => "150","iso" => "NL","name" => "Netherlands","iso3" => "NLD"),
            array("ID" => "151","iso" => "AN","name" => "Netherlands Antilles","iso3" => "ANT"),
            array("ID" => "152","iso" => "NC","name" => "New Caledonia","iso3" => "NCL"),
            array("ID" => "153","iso" => "NZ","name" => "New Zealand","iso3" => "NZL"),
            array("ID" => "154","iso" => "NI","name" => "Nicaragua","iso3" => "NIC"),
            array("ID" => "155","iso" => "NE","name" => "Niger","iso3" => "NER"),
            array("ID" => "156","iso" => "NG","name" => "Nigeria","iso3" => "NGA"),
            array("ID" => "157","iso" => "NU","name" => "Niue","iso3" => "NIU"),
            array("ID" => "158","iso" => "NF","name" => "Norfolk Island","iso3" => "NFK"),
            array("ID" => "159","iso" => "MP","name" => "Northern Mariana Islands","iso3" => "MNP"),
            array("ID" => "160","iso" => "NO","name" => "Norway","iso3" => "NOR"),
            array("ID" => "161","iso" => "OM","name" => "Oman","iso3" => "OMN"),
            array("ID" => "162","iso" => "PK","name" => "Pakistan","iso3" => "PAK"),
            array("ID" => "163","iso" => "PW","name" => "Palau","iso3" => "PLW"),
            array("ID" => "164","iso" => "PS","name" => "Palestinian Territory, Occupied","iso3" => ""),
            array("ID" => "165","iso" => "PA","name" => "Panama","iso3" => "PAN"),
            array("ID" => "166","iso" => "PG","name" => "Papua New Guinea","iso3" => "PNG"),
            array("ID" => "167","iso" => "PY","name" => "Paraguay","iso3" => "PRY"),
            array("ID" => "168","iso" => "PE","name" => "Peru","iso3" => "PER"),
            array("ID" => "169","iso" => "PH","name" => "Philippines","iso3" => "PHL"),
            array("ID" => "170","iso" => "PN","name" => "Pitcairn","iso3" => "PCN"),
            array("ID" => "171","iso" => "PL","name" => "Poland","iso3" => "POL"),
            array("ID" => "172","iso" => "PT","name" => "Portugal","iso3" => "PRT"),
            array("ID" => "173","iso" => "PR","name" => "Puerto Rico","iso3" => "PRI"),
            array("ID" => "174","iso" => "QA","name" => "Qatar","iso3" => "QAT"),
            array("ID" => "175","iso" => "RE","name" => "Reunion","iso3" => "REU"),
            array("ID" => "176","iso" => "RO","name" => "Romania","iso3" => "ROM"),
            array("ID" => "177","iso" => "RU","name" => "Russian Federation","iso3" => "RUS"),
            array("ID" => "178","iso" => "RW","name" => "Rwanda","iso3" => "RWA"),
            array("ID" => "179","iso" => "SH","name" => "Saint Helena","iso3" => "SHN"),
            array("ID" => "180","iso" => "KN","name" => "Saint Kitts and Nevis","iso3" => "KNA"),
            array("ID" => "181","iso" => "LC","name" => "Saint Lucia","iso3" => "LCA"),
            array("ID" => "182","iso" => "PM","name" => "Saint Pierre and Miquelon","iso3" => "SPM"),
            array("ID" => "183","iso" => "VC","name" => "Saint Vincent and the Grenadines","iso3" => "VCT"),
            array("ID" => "184","iso" => "WS","name" => "Samoa","iso3" => "WSM"),
            array("ID" => "185","iso" => "SM","name" => "San Marino","iso3" => "SMR"),
            array("ID" => "186","iso" => "ST","name" => "Sao Tome and Principe","iso3" => "STP"),
            array("ID" => "187","iso" => "SA","name" => "Saudi Arabia","iso3" => "SAU"),
            array("ID" => "188","iso" => "SN","name" => "Senegal","iso3" => "SEN"),
            array("ID" => "189","iso" => "CS","name" => "Serbia and Montenegro","iso3" => ""),
            array("ID" => "190","iso" => "SC","name" => "Seychelles","iso3" => "SYC"),
            array("ID" => "191","iso" => "SL","name" => "Sierra Leone","iso3" => "SLE"),
            array("ID" => "192","iso" => "SG","name" => "Singapore","iso3" => "SGP"),
            array("ID" => "193","iso" => "SK","name" => "Slovakia","iso3" => "SVK"),
            array("ID" => "194","iso" => "SI","name" => "Slovenia","iso3" => "SVN"),
            array("ID" => "195","iso" => "SB","name" => "Solomon Islands","iso3" => "SLB"),
            array("ID" => "196","iso" => "SO","name" => "Somalia","iso3" => "SOM"),
            array("ID" => "197","iso" => "ZA","name" => "South Africa","iso3" => "ZAF"),
            array("ID" => "198","iso" => "GS","name" => "South Georgia and the South Sandwich Islands","iso3" => ""),
            array("ID" => "199","iso" => "ES","name" => "Spain","iso3" => "ESP"),
            array("ID" => "200","iso" => "LK","name" => "Sri Lanka","iso3" => "LKA"),
            array("ID" => "201","iso" => "SD","name" => "Sudan","iso3" => "SDN"),
            array("ID" => "202","iso" => "SR","name" => "Suriname","iso3" => "SUR"),
            array("ID" => "203","iso" => "SJ","name" => "Svalbard and Jan Mayen","iso3" => "SJM"),
            array("ID" => "204","iso" => "SZ","name" => "Swaziland","iso3" => "SWZ"),
            array("ID" => "205","iso" => "SE","name" => "Sweden","iso3" => "SWE"),
            array("ID" => "206","iso" => "CH","name" => "Switzerland","iso3" => "CHE"),
            array("ID" => "207","iso" => "SY","name" => "Syrian Arab Republic","iso3" => "SYR"),
            array("ID" => "208","iso" => "TW","name" => "Taiwan, Province of China","iso3" => "TWN"),
            array("ID" => "209","iso" => "TJ","name" => "Tajikistan","iso3" => "TJK"),
            array("ID" => "210","iso" => "TZ","name" => "Tanzania, United Republic of","iso3" => "TZA"),
            array("ID" => "211","iso" => "TH","name" => "Thailand","iso3" => "THA"),
            array("ID" => "212","iso" => "TL","name" => "Timor-Leste","iso3" => ""),
            array("ID" => "213","iso" => "TG","name" => "Togo","iso3" => "TGO"),
            array("ID" => "214","iso" => "TK","name" => "Tokelau","iso3" => "TKL"),
            array("ID" => "215","iso" => "TO","name" => "Tonga","iso3" => "TON"),
            array("ID" => "216","iso" => "TT","name" => "Trinidad and Tobago","iso3" => "TTO"),
            array("ID" => "217","iso" => "TN","name" => "Tunisia","iso3" => "TUN"),
            array("ID" => "218","iso" => "TR","name" => "Turkey","iso3" => "TUR"),
            array("ID" => "219","iso" => "TM","name" => "Turkmenistan","iso3" => "TKM"),
            array("ID" => "220","iso" => "TC","name" => "Turks and Caicos Islands","iso3" => "TCA"),
            array("ID" => "221","iso" => "TV","name" => "Tuvalu","iso3" => "TUV"),
            array("ID" => "222","iso" => "UG","name" => "Uganda","iso3" => "UGA"),
            array("ID" => "223","iso" => "UA","name" => "Ukraine","iso3" => "UKR"),
            array("ID" => "224","iso" => "AE","name" => "United Arab Emirates","iso3" => "ARE"),
            array("ID" => "225","iso" => "GB","name" => "United Kingdom","iso3" => "GBR"),
            array("ID" => "226","iso" => "US","name" => "United States","iso3" => "USA"),            
            array("ID" => "228","iso" => "UY","name" => "Uruguay","iso3" => "URY"),
            array("ID" => "229","iso" => "UZ","name" => "Uzbekistan","iso3" => "UZB"),
            array("ID" => "230","iso" => "VU","name" => "Vanuatu","iso3" => "VUT"),
            array("ID" => "231","iso" => "VE","name" => "Venezuela","iso3" => "VEN"),
            array("ID" => "232","iso" => "VN","name" => "Viet Nam","iso3" => "VNM"),
            array("ID" => "233","iso" => "VG","name" => "Virgin Islands, British","iso3" => "VGB"),
            array("ID" => "234","iso" => "VI","name" => "Virgin Islands, U.s.","iso3" => "VIR"),
            array("ID" => "235","iso" => "WF","name" => "Wallis and Futuna","iso3" => "WLF"),
            array("ID" => "236","iso" => "EH","name" => "Western Sahara","iso3" => "ESH"),
            array("ID" => "237","iso" => "YE","name" => "Yemen","iso3" => "YEM"),
            array("ID" => "238","iso" => "ZM","name" => "Zambia","iso3" => "ZMB"),
            array("ID" => "239","iso" => "ZW","name" => "Zimbabwe","iso3" => "ZWE"),
		);

		DB::table('countries')->insert($countries);

        DB::table('states')->delete();
        $states = array(
            array("ID" => "1","name" => "Alaska","state_code" => "AK","country_code" => "226"),
            array("ID" => "2","name" => "Alabama","state_code" => "AL","country_code" => "226"),
            array("ID" => "3","name" => "American Samoa","state_code" => "AS","country_code" => "226"),
            array("ID" => "4","name" => "Arizona","state_code" => "AZ","country_code" => "226"),
            array("ID" => "5","name" => "Arkansas","state_code" => "AR","country_code" => "226"),
            array("ID" => "6","name" => "California","state_code" => "CA","country_code" => "226"),
            array("ID" => "7","name" => "Colorado","state_code" => "CO","country_code" => "226"),
            array("ID" => "8","name" => "Connecticut","state_code" => "CT","country_code" => "226"),
            array("ID" => "9","name" => "Delaware","state_code" => "DE","country_code" => "226"),
            array("ID" => "10","name" => "District of Columbia","state_code" => "DC","country_code" => "226"),
            array("ID" => "11","name" => "Florida","state_code" => "FL","country_code" => "226"),
            array("ID" => "12","name" => "Georgia","state_code" => "GA","country_code" => "226"),
            array("ID" => "13","name" => "Guam","state_code" => "GU","country_code" => "226"),
            array("ID" => "14","name" => "Hawaii","state_code" => "HI","country_code" => "226"),
            array("ID" => "15","name" => "Idaho","state_code" => "ID","country_code" => "226"),
            array("ID" => "16","name" => "Illinois","state_code" => "IL","country_code" => "226"),
            array("ID" => "17","name" => "Indiana","state_code" => "IN","country_code" => "226"),
            array("ID" => "18","name" => "Iowa","state_code" => "IA","country_code" => "226"),
            array("ID" => "19","name" => "Kansas","state_code" => "KS","country_code" => "226"),
            array("ID" => "20","name" => "Kentucky","state_code" => "KY","country_code" => "226"),
            array("ID" => "21","name" => "Louisiana","state_code" => "LA","country_code" => "226"),
            array("ID" => "22","name" => "Maine","state_code" => "ME","country_code" => "226"),
            array("ID" => "23","name" => "Maryland","state_code" => "MD","country_code" => "226"),
            array("ID" => "24","name" => "Massachusetts","state_code" => "MA","country_code" => "226"),
            array("ID" => "25","name" => "Michigan","state_code" => "MI","country_code" => "226"),
            array("ID" => "26","name" => "Minnesota","state_code" => "MN","country_code" => "226"),
            array("ID" => "27","name" => "Mississippi","state_code" => "MS","country_code" => "226"),
            array("ID" => "28","name" => "Missouri","state_code" => "MO","country_code" => "226"),
            array("ID" => "29","name" => "Montana","state_code" => "MT","country_code" => "226"),
            array("ID" => "30","name" => "Nebraska","state_code" => "NE","country_code" => "226"),
            array("ID" => "31","name" => "Nevada","state_code" => "NV","country_code" => "226"),
            array("ID" => "32","name" => "New Hampshire","state_code" => "NH","country_code" => "226"),
            array("ID" => "33","name" => "New Jersey","state_code" => "NJ","country_code" => "226"),
            array("ID" => "34","name" => "New Mexico","state_code" => "NM","country_code" => "226"),
            array("ID" => "35","name" => "New York","state_code" => "NY","country_code" => "226"),
            array("ID" => "36","name" => "North Carolina","state_code" => "NC","country_code" => "226"),
            array("ID" => "37","name" => "North Dakota","state_code" => "ND","country_code" => "226"),
            array("ID" => "38","name" => "Northern Mariana Islands","state_code" => "MP","country_code" => "226"),
            array("ID" => "39","name" => "Ohio","state_code" => "OH","country_code" => "226"),
            array("ID" => "40","name" => "Oklahoma","state_code" => "OK","country_code" => "226"),
            array("ID" => "41","name" => "Oregon","state_code" => "OR","country_code" => "226"),
            array("ID" => "42","name" => "Palau","state_code" => "PW","country_code" => "226"),
            array("ID" => "43","name" => "Pennsylvania","state_code" => "PA","country_code" => "226"),
            array("ID" => "44","name" => "Puerto Rico","state_code" => "PR","country_code" => "226"),
            array("ID" => "45","name" => "Rhode Island","state_code" => "RI","country_code" => "226"),
            array("ID" => "46","name" => "South Carolina","state_code" => "SC","country_code" => "226"),
            array("ID" => "47","name" => "South Dakota","state_code" => "SD","country_code" => "226"),
            array("ID" => "48","name" => "Tennessee","state_code" => "TN","country_code" => "226"),
            array("ID" => "49","name" => "Texas","state_code" => "TX","country_code" => "226"),
            array("ID" => "50","name" => "Utah","state_code" => "UT","country_code" => "226"),
            array("ID" => "51","name" => "Vermont","state_code" => "VT","country_code" => "226"),
            array("ID" => "52","name" => "Virgin Islands","state_code" => "VI","country_code" => "226"),
            array("ID" => "53","name" => "Virginia","state_code" => "VA","country_code" => "226"),
            array("ID" => "54","name" => "Washington","state_code" => "WA","country_code" => "226"),
            array("ID" => "55","name" => "West Virginia","state_code" => "WV","country_code" => "226"),
            array("ID" => "56","name" => "Wisconsin","state_code" => "WI","country_code" => "226"),
            array("ID" => "57","name" => "Wyoming","state_code" => "WY","country_code" => "226"),
            array("ID" => "58","name" => "Alberta","state_code" => "AB","country_code" => "38"),
            array("ID" => "59","name" => "British Columbia","state_code" => "BC","country_code" => "38"),
            array("ID" => "60","name" => "Manitoba","state_code" => "MB","country_code" => "38"),
            array("ID" => "61","name" => "New Brunswick","state_code" => "NB","country_code" => "38"),
            array("ID" => "62","name" => "Newfoundland and Labrador","state_code" => "NL","country_code" => "38"),
            array("ID" => "63","name" => "Northwest Territories","state_code" => "NT","country_code" => "38"),
            array("ID" => "64","name" => "Nova Scotia","state_code" => "NS","country_code" => "38"),
            array("ID" => "65","name" => "Nunavut","state_code" => "NU","country_code" => "38"),
            array("ID" => "66","name" => "Ontario","state_code" => "ON","country_code" => "38"),
            array("ID" => "67","name" => "Prince Edward Island","state_code" => "PE","country_code" => "38"),
            array("ID" => "68","name" => "Quebec","state_code" => "QC","country_code" => "38"),
            array("ID" => "69","name" => "Saskatchewan","state_code" => "SK","country_code" => "38"),
            array("ID" => "70","name" => "Yukon Territory","state_code" => "YT","country_code" => "38"),            
        );

        DB::table('states')->insert($states);
    }
}
